name 'kreczko-frontiersquid'
version '0.0.1'

author 'kreczko'
license 'Apache License, Version 2.0'
project_page 'https://github.com/HEP-Puppet/puppet-frontiersquid'
source 'git@github.com:HEP-Puppet/puppet-frontiersquid.git'
summary 'A Puppet module for the installation and setup of a frontier squid'
description 'A Puppet module for the installation and setup of a frontier squid'
dependency 'traylenator/cvmfs', '>=0.0.2'
